baseURL = 'https://manavrupanitechnophile.netlify.app/'
languageCode = 'en-us'
title = 'technophile'
theme = "hugo-PaperMod"

[menu]
  [[menu.main]]
    identifier = "About Me"
    name = "About Me"
    url = "/about/"
    weight = 10

[deployment]
  [[deployment.targets]]
    # An arbitrary name for this target.
    name = "production"
    # URL specifies the Go Cloud Development Kit URL to deploy to.
    URL = "<FILL ME IN>"
