baseURL = 'https://github.com/ManavRupani/Blog.github.io'
languageCode = 'en-us'
title = 'technophile'
theme = "paper"

[menu]
  [[menu.main]]
    identifier = "About Me"
    name = "About Me"
    url = "/about/"
    weight = 10
